---
documentation:
  description: Options for neural network creation, training and evaluation.

  authors:
    - iglesias-suarez_fernando
    - solino-fernandez_breixo
    - kuehbacher_birgit

  references:
    - acknow_project

  projects:
    - usmile


# Common
# ======
# Specifications
analysis: 'single'
spcam_parents: [ 'qbp','tbp','vbp','ps','solin','shflx','lhflx' ]
spcam_children: [ 'phq','tphystnd','fsnt','fsns','flnt','flns','prect' ]
independence_test: "None"
pc_alphas: [ 0.01 ]
region: [ [ -90,90 ] , [ 0.,359. ] ]
lim_levels: False
# Model levels : [3.64, 7.59, 14.36, 24.61, 38.27, 54.6, 72.01, 87.82, 103.32, 121.55, 142.99, 168.23, 197.91, 232.83, 273.91, 322.24, 379.1, 445.99, 524.69, 609.78, 691.39, 763.4, 820.86, 859.53, 887.02, 912.64, 936.2, 957.49, 976.33, 992.56]
target_levels: False
output_folder: "./SPCAM_Rasp_causal_links_3mth_v2"
plots_folder: "plots"
verbosity: 1
output_file_pattern:
  single: "{var_name}_{level}_lat-{lat}_lon-{lon}_{ind_test}_{experiment}.obj"
  concat: "{var_name}_{level}_{lat1}-{lat2}_{lon1}-{lon2}_{ind_test}_{experiment}.obj"
## DATASETS. 
data_folder: "./SPCAM_tb_recons"
experiment: "2021_09_02_TRAIN_For_Nando"
shifting: 0 # 0 (no shifting); 1 (output t-1)


# Aggregated analysis
# ===================
thresholds: [ .59 ]
area_weighted: True # True; False
pdf: True # True; False
aggregate_folder: "./aggregate_pdf"
plot_file_pattern:
  single: "{var_name}_{level}_lat{lat}_lon{lon}_a{pc_alpha}_{ind_test}_{experiment}.png"
  concat: "{var_name}_{level}_{lat1}-{lat2}_{lon1}-{lon2}_a{pc_alpha}_{ind_test}_{experiment}.png"


# Neural Network configuration
# ============================

nn_type: "PreMaskNet"

nn_output_path: output

input_order: [ qbp, tbp, vbp, ps, solin, shflx, lhflx ]
output_order: [ phq, tphystnd, fsnt, fsns, flnt, flns, prect ]

hidden_layers: [ 256,256,256,256,256,256,256,256,256 ]
activation: LeakyReLU

# Training configuration
# ----------------------
## DATASETS.
train_data_folder: "./SPCAM_tb_preproc"
train_data_fn: 2021_09_02_TRAIN_For_Nando_shuffle.nc
valid_data_fn: 2021_09_02_VALID_For_Nando.nc
epochs: 9
train_verbose: 2 # 0:Silent; 1:Continuous update; 2:Summary on epochs
tensorboard_folder: output/tensorboard

# From Tom https://github.com/tbeucler/CBRAIN-CAM/tree/master/notebooks/tbeucler_devlog/UW_DATA
normalization_folder: "./SPCAM_tb_preproc"
normalization_fn: 001_norm_for_tb_dataset.nc

input_sub: mean
input_div: maxrs
out_scale_dict_folder: ./config/scale_dicts/
out_scale_dict_fn: 002_pnas_scaling.pkl
batch_size: 1024  #1024

# Learning Rate Scheduler
# Exponential schedule (original Rasp et al.)
lr_schedule: "exponential"
init_lr: 0.001 # From train.py (default)
step_lr: 3 # From 006_8col_pnas_exact.yml
divide_lr: 5 # From train.py (default)

# Early Stopping
train_patience: 5


# PreMaskNet
# ----------------------
lambda_sparsity: 0.001
relu_alpha: 0.3

distribute_strategy: "" # mirrored for using tf.distribute.MirroredStrategy or nothing for training on single GPU

additional_val_datasets:
  - { name: "plus_4K", data: "test/test_data/2022_02_07_TEST_For_Nando_p4K_perc0-1.nc" }
  - { name: "minus_4K", data: "test/test_data/2022_02_07_TEST_For_Nando_m4K_perc0-1.nc" }

kernel_initializer_input_layers: "RandomNormal"
input_init_random_normal_mean: 0.0
input_init_random_normal_std: 0.01

kernel_initializer_hidden_layers: "GlorotUniform"

kernel_initializer_output_layers: "GlorotUniform"


# Diagnostic configuration
# ----------------------
## DATASETS.
test_data_folder: "./SPCAM_tb_preproc"
test_data_fn: 2021_09_02_TEST_For_Nando.nc
# Diagnostics
diagnostics: [ 'map' ]
diagnostics_time: [ 'mean' ] # snapshot: int; time-mean: 'mean'